name: Build Python with Embed

on: [push]

jobs:
  build-win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Generate Embed
        run: embed.cmd
        shell: cmd

      - name: Gen zip files
        run: |
          tar cfv model-train-embed-win32.zip *.py assets py32 run32* *.md _*
          tar cfv model-train-embed-win64.zip *.py assets py64 run64* *.md _*

      - uses: actions/upload-artifact@v2
        with:
          name: model-training-win64
          path: model-train-embed-win64.zip

      - uses: actions/upload-artifact@v2
        with:
          name: model-training-win32
          path: model-train-embed-win32.zip
