name: Build Python with Embed

on: [push]

jobs:
  build-win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Generate Embed
        run: embed.cmd
        shell: cmd

      - uses: actions/upload-artifact@v2
        with:
          name: model-training-win64
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/py32
            !${{ github.workspace }}/run32.cmd

      - uses: actions/upload-artifact@v2
        with:
          name: model-training-win32
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/py64
            !${{ github.workspace }}/run64.cmd
