name: Build Python with Embed

on: [push]

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            py32
            py64
          key: ${{ runner.os }}-${{ hashFiles('**/embed.cmd') }}-${{ hashFiles('**/requirements.txt') }}

      - name: Generate Embed
        run: embed.cmd
        shell: cmd

      - name: Gen zip files
        run: |
          tar cf model-train-embed-win32.zip app.py assets py32 run32* *.md _*
          tar cf model-train-embed-win64.zip app.py assets py64 run64* *.md _*

      - uses: actions/upload-artifact@v2
        with:
          name: model-training-win64
          path: model-train-embed-win64.zip

      - uses: actions/upload-artifact@v2
        with:
          name: model-training-win32
          path: model-train-embed-win32.zip

      - name: Cleaning
        run: |
          cd py32
          del *.py
          cd ..
          cd py64
          del *.py
          cd ..
